get_token = "/auth"
get_all_bookings = "/booking"
post_create_booking = "/booking"
put_update_booking="/booking/<bookingid>"
patch_partial_update_booking = "/booking/<bookingid>"
get_bookings_by_name = "/booking?firstname=<firstname>&lastname=<lastname>"
get_bookings_by_date = "/booking?checkin=<checkin>&checkout=<checkout>"
health_check_of_api = "/ping"
delete_booking_id = "/booking/<bookingid>"